import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { projects, type Project } from '../data/siteData'
import { Eyebrow, Reveal } from '../components/UI'

export default function CaseStudy(){
  const {slug}=useParams()
  const i=projects.findIndex(p=>p.slug===slug)
  if(i<0)return <Navigate to="/work"/>
  const p=projects[i]
  const prev=projects[(i-1+projects.length)%projects.length]
  const next=projects[(i+1)%projects.length]
  return <article className="case">
     <section className="case-hero section"><Reveal><Link to="/work" className="back"><ArrowLeft/> All work</Link><Eyebrow>{p.number} — {p.category}</Eyebrow><h1>{p.name}</h1><p className="page-lead">{p.description}</p>{p.label&&<span className="case-label">{p.label}</span>}</Reveal>{p.slug!=='social-media-design'&&<Reveal className={`case-cover${p.slug==='veralya' ? ' veralya-case-cover' : ''}`}><img src={p.caseHero||p.image} alt={`${p.name} hero visual`}/></Reveal>}</section>
    <section className="case-meta section"><div><small>ROLE</small><b>{p.role||'[ADD ROLE]'}</b></div><div><small>DURATION</small><b>{p.duration||'[ADD DURATION]'}</b></div><div><small>PROJECT TYPE</small><b>{p.type||'[ADD PROJECT TYPE]'}</b></div><div><small>TOOLS</small><b>{p.tools.join(', ')}</b></div><div><small>YEAR</small><b>{p.year||'[ADD YEAR]'}</b></div></section>
    {p.note&&<section className="section"><div className="disclosure"><strong>Project disclosure</strong><p>{p.note}</p></div></section>}
    {p.slug==='veralya'?<VeralyaCase p={p}/>:p.slug==='baymax-sky-ride'?<BaymaxCase/>:p.slug==='nft-marketplace'?<NftCase/>:p.slug==='w-water-bottle'?<WaterBottleCase p={p}/>:p.slug==='celeste-tea'?<CelesteCase p={p}/>:p.slug==='alpenoire'?<AlpenoireCase p={p}/>:p.slug==='movie-rental-admin'?<MovieRentalCase p={p}/>:p.slug==='social-media-design'?<SocialMediaCollection/>:<PlaceholderCase p={p}/>} 
    <nav className="case-nav section"><Link to={`/work/${prev.slug}`}><ArrowLeft/><small>Previous project</small><b>{prev.name}</b></Link><Link to={`/work/${next.slug}`}><small>Next project</small><b>{next.name}</b><ArrowRight/></Link></nav>
  </article>
}

function VeralyaCase({p}:{p:Project}){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Project overview</span><h2>Elegance, refined into a complete system.</h2><p>VERALYA is a self-initiated premium skincare branding project created to explore how a new beauty brand can build a sophisticated and consistent visual identity. The concept focuses on elegance, simplicity, and a luxurious self-care experience.</p></Reveal>
    <Reveal><span className="chapter">02 / The challenge</span><h2>Premium, trustworthy, feminine, and modern.</h2><p>The goal was to create a skincare brand that feels premium, trustworthy, feminine, and modern while maintaining a consistent identity across multiple products. The packaging also needed to clearly connect all five products as part of one skincare collection.</p></Reveal>
    <Reveal><span className="chapter">03 / The solution</span><h2>A rich and refined visual language.</h2><p>I developed a visual system using deep burgundy, warm cream, amber tones, and metallic gold accents. Minimal typography, elegant layouts, and premium packaging finishes establish VERALYA as a sophisticated skincare brand.</p></Reveal>
    <Reveal><span className="chapter">04 / Product collection</span><h2>Five products. One cohesive ritual.</h2><div className="product-list">{['Face Wash','Essence Toner','Face Serum','Body Butter','Night Cream'].map((x,i)=><span key={x}>0{i+1} — {x}</span>)}</div><p>Each product follows the same visual language while maintaining its own clear product identity.</p></Reveal>
    <Reveal><span className="chapter">05 / Brand identity</span><h2>Modern elegance and natural beauty.</h2><p>The VERALYA wordmark, leaf-inspired brand element, colour palette, typography, packaging layouts, and supporting graphics were designed to work together as one cohesive system.</p></Reveal>
    <Reveal><span className="chapter">06 / Packaging design</span><h2>Recognition through consistency.</h2><p>Burgundy surfaces, dark amber containers, cream elements, and gold detailing communicate luxury and quality. Consistent logo placement, typography, spacing, and product information create a recognizable collection.</p></Reveal>
  </section>
  <section className="case-video section"><Reveal><span className="chapter">07 / Cinematic direction</span><h2>VERALYA in motion.</h2><p>Warm lighting, tactile materials, controlled movement, and an editorial composition extend the brand’s premium character into a cinematic digital experience.</p></Reveal><video controls muted loop playsInline poster="./images/veralya-hero.png"><source src="./media/veralya-cinematic.mp4" type="video/mp4"/>Your browser does not support embedded video.</video></section>
  <section className="case-gallery section">{p.gallery?.map((x,j)=><img src={x} key={x} alt={`VERALYA campaign visual ${j+1}`} loading="lazy"/>)}</section>
  <section className="case-body section">
    <Reveal><span className="chapter">08 / Visual direction</span><h2>A clean editorial campaign language.</h2><p>Product mockups and campaign visuals use soft lighting, minimal compositions, premium materials, and warm tones to reinforce the brand’s elegant personality across digital marketing and social media.</p></Reveal>
    <Reveal><span className="chapter">09 / My role</span><h2>From research to presentation.</h2><p>Brand Research · Brand Identity · Logo Development · Colour &amp; Typography · Packaging Design · Product Mockups · Art Direction · Digital Presentation</p><div className="tools"><span>Affinity Designer</span><span>Affinity Photo</span><span>Typography</span></div></Reveal>
    <Reveal className="wide-chapter"><span className="chapter">10 / Outcome</span><h2>A cohesive premium skincare identity.</h2><p>The final result demonstrates how VERALYA could appear across product packaging, promotional visuals, digital platforms, and conceptual brand campaigns—creating a premium visual experience around the idea of “Elegance Redefined.”</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal>
  </section>
  </>}

function BaymaxCase(){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Project overview</span><h2>Turning virtual flight into a physical experience.</h2><p>Baymax Sky Ride is an immersive 360° VR flight experience inspired by Big Hero 6. The project simulates the feeling of flying through a city while riding Baymax by combining virtual reality with physical motion, wind feedback, and environmental audio.</p></Reveal>
    <Reveal><span className="chapter">02 / The challenge</span><h2>Moving beyond screen-based VR.</h2><p>The goal was to create an experience users could physically feel. Our concept transformed a vertically moving platform into a synchronized VR flight system, allowing the physical setup to respond to movement inside the virtual environment.</p></Reveal>
    <Reveal><span className="chapter">03 / The experience</span><h2>Explore the city with natural control.</h2><p>Users wear a Meta Quest headset and navigate through a virtual city using VR controllers. They can freely explore, change direction, ascend, descend, and look around naturally through head tracking. When Baymax moves vertically in VR, the physical platform moves with it while wind and environmental sounds strengthen the sensation of flight.</p></Reveal>
    <Reveal><span className="chapter">04 / Interaction &amp; immersion</span><h2>A multisensory feedback system.</h2><div className="feedback-grid"><div><b>Visual</b><span>First-person city flight and dynamic environments</span></div><div><b>Motion</b><span>Synchronized vertical platform movement</span></div><div><b>Wind</b><span>Fans responding to flight activity</span></div><div><b>Audio</b><span>City ambience, wind sounds, and flight effects</span></div></div><p>Together, these feedback layers create a stronger sense of presence and realism.</p></Reveal>
    <Reveal className="wide-chapter"><span className="chapter">05 / Technology</span><h2>Connecting Unity to physical computing.</h2><p>The system uses Unity, Meta Quest, XR Interaction Toolkit, Arduino, DC motors, a motor driver, serial communication, and a wind fan system. Unity processes flight data and sends altitude information to the Arduino, which controls the physical motion system.</p><div className="tech-flow"><span>Meta Quest input</span><i>→</i><span>Unity flight system</span><i>→</i><span>Serial communication</span><i>→</i><span>Arduino controller</span><i>→</i><span>Motion + wind feedback</span></div></Reveal>
  </section>
  <section className="case-focus section"><div><small>TOOLS</small><p>Unity · Meta Quest · XR Interaction Toolkit · Arduino</p></div><div><small>PROJECT TYPE</small><p>University Group Project</p></div><div><small>FOCUS</small><p>VR Development · Interaction Design · Immersive Experience Design</p></div></section>
  <section className="case-body section"><Reveal className="wide-chapter"><span className="chapter">06 / Outcome</span><h2>Virtual movement, made tangible.</h2><p>Baymax Sky Ride demonstrates how VR, physical computing, interaction design, and multisensory feedback can work together to create a more immersive entertainment experience. The project explores turning virtual movement into a physical experience rather than relying only on visuals.</p></Reveal></section>
  </>}

function NftCase(){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Overview</span><h2>Designing a bold digital-collectibles experience.</h2><p>This individual project explores the design of a modern NFT marketplace where users can discover, explore, and interact with digital collectibles. The goal was to strengthen my understanding of colour theory, visual hierarchy, interface design, and Figma prototyping.</p></Reveal>
    <Reveal><span className="chapter">02 / Design approach</span><h2>A futuristic visual language with clear hierarchy.</h2><p>I created a bold visual style suited to the NFT and digital-art space. Colour combinations, contrast, typography, spacing, and card layouts were carefully considered to make the interface engaging while maintaining readability and usability.</p></Reveal>
    <Reveal><span className="chapter">03 / Figma system</span><h2>Reusable components and consistent layouts.</h2><p>The complete interface was designed in Figma, including reusable components, navigation elements, NFT cards, marketplace screens, and consistent layout rules.</p></Reveal>
    <Reveal><span className="chapter">04 / Interactive prototyping</span><h2>Connecting the key user flows.</h2><p>An interactive prototype demonstrates navigation and the overall user flow between important screens, turning the static visual system into a testable digital experience.</p></Reveal>
  </section>
  <section className="case-video section"><Reveal><span className="chapter">05 / Prototype demonstration</span><h2>The marketplace in motion.</h2><p>The recorded prototype shows the interface, transitions, navigation, and screen-to-screen flow created in Figma.</p></Reveal><video controls muted loop playsInline poster="./images/nft-marketplace.png"><source src="./media/nft-marketplace-prototype.mp4" type="video/mp4"/>Your browser does not support embedded video.</video></section>
  <section className="case-focus section"><div><small>PROJECT TYPE</small><p>Individual Project</p></div><div><small>TOOLS</small><p>Figma</p></div><div><small>FOCUS</small><p>Colour Theory · UI Design · Interactive Prototyping</p></div></section>
  <section className="case-body section">
    <Reveal><span className="chapter">06 / Key skills</span><h2>Skills demonstrated.</h2><div className="product-list">{['Colour theory and visual consistency','UI layout and visual hierarchy','Figma components and interface design','Interactive prototyping','User flow and navigation design'].map((x,i)=><span key={x}>0{i+1} — {x}</span>)}</div></Reveal>
    <Reveal><span className="chapter">07 / Outcome</span><h2>From visual concept to interactive experience.</h2><p>The project improved my ability to transform a visual concept into a consistent and interactive digital experience while developing stronger Figma UI design and prototyping skills.</p></Reveal>
  </section>
  </>}

function WaterBottleCase({p}:{p:Project}){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Overview</span><h2>One identity, designed for three lifestyles.</h2><p>W is a self-initiated water-bottle brand created to explore how one visual identity can adapt across different user lifestyles. The project features three product variations for students, gym users, and office professionals while maintaining one consistent premium brand language.</p></Reveal>
    <Reveal><span className="chapter">02 / Target audience</span><h2>Students, gym users, and office professionals.</h2><p>Each product direction responds to a different routine and mindset. The visual communication changes to suit its audience, while the logo, matte-black finish, core palette, and premium presentation keep the collection recognizable.</p></Reveal>
    <Reveal><span className="chapter">03 / Design approach</span><h2>Minimal, monochrome, and premium.</h2><p>The identity uses a minimal black, white, and ash colour palette. Every variation shares the W logo and matte-black product style, supported by different messaging and visual treatments for its intended audience.</p></Reveal>
    <Reveal><span className="chapter">04 / Product variations</span><h2>Different messages, one core identity.</h2><div className="product-list"><span>01 — Student: “Think. Work. Win.”</span><span>02 — Gym: “Built for Greatness.”</span><span>03 — Office: Minimal professional edition</span></div></Reveal>
    <Reveal><span className="chapter">05 / Visual development</span><h2>From product concept to campaign imagery.</h2><p>I developed product concepts, packaging visuals, promotional compositions, and campaign-style imagery to show how the brand could appear across marketing applications. Strong contrast, minimal typography, and cinematic product presentation reinforce the identity.</p></Reveal>
    <Reveal><span className="chapter">06 / Design system</span><h2>Consistency without repetition.</h2><p>The system balances shared brand assets with audience-specific decisions, allowing every bottle to feel distinct without losing the core W identity.</p></Reveal>
  </section>
  <section className="case-gallery section">{p.gallery?.map((x,j)=><img src={x} key={x} alt={`W Water Bottle product variation ${j+1}`} loading="lazy"/>)}</section>
  <section className="case-focus section"><div><small>PROJECT TYPE</small><p>Individual Project</p></div><div><small>FOCUS</small><p>Brand Identity · Product Branding · Visual Design</p></div><div><small>TARGET AUDIENCE</small><p>Students · Gym Users · Office Professionals</p></div></section>
  <section className="case-body section">
    <Reveal><span className="chapter">07 / Key skills</span><h2>Skills demonstrated.</h2><div className="product-list">{['Brand identity development','Product branding and visual consistency','Typography and colour application','Packaging and promotional design','Target-audience-based design decisions','Art direction and product presentation'].map((x,i)=><span key={x}>0{i+1} — {x}</span>)}</div></Reveal>
    <Reveal><span className="chapter">08 / Outcome</span><h2>A flexible system with a consistent core.</h2><p>This project strengthened my ability to build a consistent brand system across multiple product variations while adapting visual communication to different target audiences without losing the brand’s core identity.</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal>
  </section>
  </>}

function CelesteCase({p}:{p:Project}){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Project overview</span><h2>Ceylon heritage, presented as a premium experience.</h2><p>CelesTea is a group branding and packaging project developed around the heritage and premium identity of Sri Lankan Ceylon tea. The concept positions tea as a sophisticated gift and export product rather than a conventional supermarket product, combining Sri Lankan cultural heritage with a luxury visual direction.</p></Reveal>
    <Reveal><span className="chapter">02 / The goal</span><h2>Authenticity, heritage, craftsmanship, and luxury.</h2><p>The goal was to create a distinctive premium tea brand that celebrates the origins of Ceylon tea while appealing to tourists, premium gift buyers, and international consumers.</p></Reveal>
    <Reveal><span className="chapter">03 / Design direction</span><h2>A rich palette rooted in history.</h2><p>Following the established CelesTea name and “From Ceylon’s peaks to your cup” tagline, I developed the visual direction using deep twilight green, antique metallic gold, and warm ochre-gold. Heritage-inspired typography, botanical ornamentation, and vintage illustration create an elegant and culturally connected identity.</p></Reveal>
    <Reveal><span className="chapter">04 / Packaging &amp; identity</span><h2>Illustration and ornament tell the origin story.</h2><p>I designed the packaging concept, colour palette, typography system, layout, illustration treatment, decorative elements, visual hierarchy, and final product presentation. A vintage-style Sri Lankan tea-plucker illustration surrounded by detailed botanical borders creates a strong connection between the product and its Ceylon heritage.</p></Reveal>
  </section>
  <section className="case-gallery section"><img src="./images/celeste-mockup.png" alt="CelesTea premium tin and presentation box mockup" loading="lazy"/><img src="./images/celeste-design.png" alt="CelesTea final packaging artwork" loading="lazy"/></section>
  <section className="case-focus section"><div><small>PROJECT TYPE</small><p>University Group Project</p></div><div><small>MY ROLE</small><p>Packaging &amp; Visual Identity Designer</p></div><div><small>AUDIENCE</small><p>Tourists · Premium Gift Buyers · International Consumers</p></div></section>
  <section className="case-body section">
    <Reveal><span className="chapter">05 / My contribution</span><h2>Complete visual identity and packaging execution.</h2><p>I was responsible for colour selection, typography, illustration direction, layout, packaging structure, decorative elements, and final design presentation. The brand name and tagline were the only elements I was not individually responsible for.</p><div className="tools"><span>Packaging Design</span><span>Colour Theory</span><span>Typography</span><span>Visual Hierarchy</span></div></Reveal>
    <Reveal><span className="chapter">06 / Outcome</span><h2>Sri Lankan heritage meets luxury packaging.</h2><p>The final result presents CelesTea as a sophisticated premium tea brand that blends Sri Lankan heritage with luxury packaging aesthetics. The project demonstrates packaging design, colour theory, typography, illustration composition, visual hierarchy, and brand presentation.</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal>
  </section>
  </>}

function AlpenoireCase({p}:{p:Project}){return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Project overview</span><h2>Alpine craftsmanship transformed into a premium brand.</h2><p>ALPENOIRE is a self-initiated premium cookie brand concept inspired by European alpine craftsmanship, warmth, and traditional baking. The project transforms a simple cookie product into a luxurious gifting and lifestyle experience.</p></Reveal>
    <Reveal><span className="chapter">02 / The goal</span><h2>Handcrafted quality with modern appeal.</h2><p>The goal was to develop a distinctive premium brand that communicates handcrafted quality, elegance, and authenticity while remaining visually appealing to a modern audience.</p></Reveal>
    <Reveal><span className="chapter">03 / Design direction</span><h2>Timeless colour and refined typography.</h2><p>A navy blue, warm cream, and gold colour palette creates a luxurious and timeless appearance. Elegant typography, minimal layouts, premium packaging, and atmospheric alpine-inspired product photography shape the visual language.</p></Reveal>
    <Reveal><span className="chapter">04 / Packaging &amp; identity</span><h2>A consistent system across an artisan collection.</h2><p>The branding extends across cookie boxes, premium product packaging, and promotional visuals. Shared illustration, typography, layout structure, and colour details keep every flavour connected to the ALPENOIRE identity.</p></Reveal>
    <Reveal className="wide-chapter"><span className="chapter">05 / Visual storytelling</span><h2>A warm European alpine world.</h2><p>Snowy landscapes, warm wooden textures, baking ingredients, atmospheric bakery environments, and editorial product photography strengthen the handcrafted European story behind the brand.</p></Reveal>
  </section>
  <section className="case-gallery section">{p.gallery?.map((x,j)=><img src={x} key={x} alt={`ALPENOIRE artisan cookie packaging variation ${j+1}`} loading="lazy"/>)}</section>
  <section className="case-focus section"><div><small>PROJECT TYPE</small><p>Self-initiated Conceptual Project</p></div><div><small>MY ROLE</small><p>Brand &amp; Packaging Designer</p></div><div><small>VISUAL DIRECTION</small><p>Navy · Warm Cream · Gold · Alpine Craftsmanship</p></div></section>
  <section className="case-body section">
    <Reveal><span className="chapter">06 / Skills demonstrated</span><h2>Building a complete premium presentation.</h2><div className="product-list">{['Brand identity','Packaging design','Colour theory','Typography','Visual storytelling','Product presentation'].map((x,i)=><span key={x}>0{i+1} — {x}</span>)}</div></Reveal>
    <Reveal><span className="chapter">07 / Outcome</span><h2>A memorable premium cookie identity.</h2><p>The final identity presents ALPENOIRE as an elegant artisan cookie brand with a consistent and memorable premium aesthetic. It demonstrates how packaging, atmosphere, and product imagery can work together to turn a familiar product into a sophisticated brand experience.</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal>
  </section>
  </>}

function MovieRentalCase({p}:{p:Project}){const screens=[['./images/movie-rental-welcome.jpeg','Authentication entry','Welcome screen and sign-in entry point'],['./images/movie-rental-role.jpeg','Role selection','Admin and user account-path selection'],['./images/movie-rental-admin-login.jpeg','Admin controls','Dedicated administrator login interface'],['./images/movie-rental-admin-dashboard.jpeg','Admin dashboard','Management overview and administrator-status controls']];return <>
  <section className="case-body section">
    <Reveal><span className="chapter">01 / Project overview</span><h2>The administrative side of a movie-rental platform.</h2><p>This was a first-year group web-development project focused on creating a movie-rental platform. My individual responsibility was the Admin section, where I worked on the interfaces required to manage and control content within the system.</p></Reveal>
    <Reveal><span className="chapter">02 / My role</span><h2>Admin UI and related development.</h2><p>My contribution focused specifically on creating the administrative side of the platform rather than the customer-facing movie-rental experience.</p></Reveal>
    <Reveal><span className="chapter">03 / The goal</span><h2>A clear and practical management experience.</h2><p>The goal of my section was to make important system information and management functions accessible through an organized interface with understandable navigation and controls.</p></Reveal>
    <Reveal><span className="chapter">04 / Design &amp; development</span><h2>Structured screens with consistent navigation.</h2><p>I designed and developed the relevant admin screens, focusing on structured layouts, readable information, clear navigation, and consistency across the dashboard. The interfaces shown below represent the part of the system I personally worked on.</p></Reveal>
  </section>
  <section className="labeled-gallery section">{screens.map(([src,title,caption])=><figure key={src}><img src={src} alt={`${title}: ${caption}`} loading="lazy"/><figcaption><b>{title}</b><span>{caption}</span></figcaption></figure>)}</section>
  <section className="case-focus section"><div><small>PROJECT STATUS</small><p>Academic Group Project · First Year</p></div><div><small>MY CONTRIBUTION</small><p>Admin Section</p></div><div><small>LIVE DEMO</small><p>Not Deployed</p></div></section>
  <section className="case-body section">
    <Reveal><span className="chapter">05 / Key focus areas</span><h2>Designing usable administrative interfaces.</h2><div className="product-list">{['Admin Dashboard UI','Content-management interfaces','Navigation','Information hierarchy','Usability','Front-end implementation'].map((x,i)=><span key={x}>0{i+1} — {x}</span>)}</div></Reveal>
    <Reveal><span className="chapter">06 / Outcome</span><h2>Practical experience building a working interface.</h2><p>This project strengthened my understanding of web development, dashboard design, UI structure, teamwork, and GitHub-based development by turning interface ideas into part of a working application.</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal>
  </section>
  </>}

function SocialMediaCollection(){const designs=[['./images/burger-poster.png','Promotional campaign','Food promotion and offer-focused advertisement'],['./images/strawberry-poster.png','Product advertisement','Bold smoothie promotion and compositing experiment'],['./images/fashion-poster.png','Editorial visual','Fashion-focused typography and image treatment'],['./images/mojito-poster.png','Beverage campaign','Fresh product composition with motion and splash effects']];return <>
  <section className="collection-intro section"><Reveal><span className="chapter">Curated collection</span><h2>Visual content across different industries and styles.</h2><p>This is a selected gallery of social media graphics rather than one individual brand case study. The collection demonstrates promotional design, campaign thinking, image composition, typography, colour, and platform-focused visual creativity.</p><div className="tools"><span>Adobe Photoshop</span><span>Affinity Designer</span><span>Affinity Photo</span><span>Canva</span></div></Reveal></section>
  <section className="social-gallery section">{designs.map(([src,title,caption],i)=><figure key={src}><div><img src={src} alt={`${title}: ${caption}`} loading="lazy"/><span>0{i+1}</span></div><figcaption><b>{title}</b><p>{caption}</p></figcaption></figure>)}</section>
  </>}

function PlaceholderCase({p}:{p:Project}){return <>
  <section className="case-body section"><Reveal><span className="chapter">01 / Context</span><h2>The challenge</h2><p>[Add the project problem, background, constraints, and opportunity.]</p></Reveal><Reveal><span className="chapter">02 / Audience</span><h2>Designing for the right people</h2><p>[Add target-audience insights, user needs, and research.]</p></Reveal><Reveal className="wide-chapter"><span className="chapter">03 / Process</span><h2>From early thinking to final system</h2><p>[Add strategy, sketches, wireframes, concept development, iteration, and decisions.]</p></Reveal></section>
  <section className="case-gallery section"><img src={p.image} alt={`${p.name} final design`} loading="lazy"/>{p.gallery?.map((x,j)=><img src={x} key={x} alt={`${p.name} application ${j+1}`} loading="lazy"/>)}</section>
  <section className="case-body section"><Reveal><span className="chapter">04 / Outcome</span><h2>Final design &amp; applications</h2><p>[Describe the completed system and verified outcomes.]</p></Reveal><Reveal><span className="chapter">05 / Reflection</span><h2>What I learned</h2><p>[Add honest reflections and lessons learned.]</p>{p.links.map(l=><a key={l.label} className="btn primary" href={l.url} target="_blank" rel="noreferrer">{l.label}<ArrowUpRight size={17}/></a>)}</Reveal></section>
  </>}
