import { ArrowDown, ArrowRight, ArrowUpRight, Palette, Download, Code2, Globe2, Mail, MapPin, Phone, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { expertise, links, projects, skills } from '../data/siteData'
import { Eyebrow, ProjectCard, Reveal } from '../components/UI'

const Linkedin = Globe2
const Behance = Palette
const Github = Code2

export default function Home(){const featured=projects.filter(p=>p.featured);return <>
  <section className="hero" id="home"><div className="orb one"/><div className="orb two"/><div className="hero-grid"/><div className="hero-copy"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="availability"><span/> Open to internships</motion.div><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.1}} className="kicker">JANADI WICKRAMASINGHE</motion.p><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.12}} className="role-line">Digital Marketer <span>·</span> Brand Designer <span>·</span> UX/UI Designer</motion.p><motion.h1 initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{delay:.15,duration:.8}}>Designing <em>Digital Experiences,<br/>Brands &amp; Ideas.</em></motion.h1><motion.p className="hero-intro" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.4}}>I combine digital marketing and brand design with UX/UI to build memorable brands and digital experiences that connect with the right audience.</motion.p><motion.div className="hero-actions" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.5}}><a className="btn primary" href="#work">View My Work <ArrowDown size={17}/></a><a className="btn secondary disabled" href={links.cv} aria-disabled="true">Download CV <Download size={17}/></a></motion.div><div className="social-row hero-social"><a href={links.linkedin} aria-label="LinkedIn"><Linkedin/></a><a href={links.behance} aria-label="Behance"><Behance/></a><a href={links.github} aria-label="GitHub"><Github/></a><a href={`mailto:${links.email}`} aria-label="Email"><Mail/></a></div></div>
 <motion.div className="portrait-wrap" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:.25,duration:.8}}><img className="portrait-image" src="./images/profile.jpeg" alt="Janadi Wickramasinghe, Interactive Media Designer"/><div className="portrait-caption"><Sparkles size={16}/><span>Ideas to impact<br/><b>through design</b></span></div></motion.div><a href="#about" className="scroll-cue"><span>Scroll to explore</span><ArrowDown size={16}/></a></section>

  <section id="about" className="section about"><Reveal><Eyebrow>About me</Eyebrow><h2>Designing Where Creativity<br/><em>Meets Technology</em></h2></Reveal><div className="about-grid"><Reveal className="about-copy"><p className="lead">I am a third-year BSc (Hons) in Creative Computing undergraduate specializing in Interactive Media at the Sri Lanka Institute of Information Technology.</p><p>My interests include brand identity, UX/UI design, digital marketing, social media design, front-end experiences, multimedia, and creative technology.</p><p>I enjoy developing projects from the initial idea and strategy through to visual design, prototyping, content creation, and final presentation. My goal is to create engaging digital experiences that are visually strong, user-focused, and supported by clear creative thinking.</p><a className="btn secondary disabled" href={links.cv}>Download CV <Download size={17}/></a></Reveal><Reveal className="facts"><div><MapPin/><small>Location</small><b>Sri Lanka</b></div><div><small>Education</small><b>BSc (Hons) in Creative Computing</b></div><div><small>Specialization</small><b>Interactive Media</b></div><div><small>Current level</small><b>Third-year undergraduate</b></div><div className="accent-fact"><small>Availability</small><b>Open to internships</b></div></Reveal></div></section>

 <section className="section expertise"><Reveal><Eyebrow>What I do</Eyebrow><h2>Creative thinking,<br/><em>built with purpose.</em></h2></Reveal><div className="expertise-grid">{expertise.map((e,i)=><Reveal key={e[0]} className="expertise-card"><span>0{i+1}</span><h3>{e[0]}</h3><p>{e[1]}</p><ArrowUpRight/></Reveal>)}</div></section>

 <section id="work" className="section work"><Reveal className="section-head"><div><Eyebrow>Featured work</Eyebrow><h2>Selected <em>Work</em></h2><p>A selection of projects across branding, UX/UI, digital marketing, social media, and web development.</p></div><Link className="text-link" to="/work">Explore all projects <ArrowRight/></Link></Reveal><div className="project-grid">{featured.map(p=><Reveal key={p.slug}><ProjectCard p={p}/></Reveal>)}</div><Link to="/work" className="btn primary centered">View More Projects <ArrowRight size={17}/></Link></section>

 <section id="skills" className="section skills"><Reveal><Eyebrow>Capabilities</Eyebrow><h2>Skills & <em>Tools</em></h2></Reveal><div className="skills-grid">{Object.entries(skills).map(([group,list],i)=><Reveal key={group} className="skill-group"><span>0{i+1}</span><h3>{group}</h3><div>{list.map(x=><b key={x}>{x}</b>)}</div></Reveal>)}</div></section>

 <section className="section timeline-section"><Reveal><Eyebrow>Journey</Eyebrow><h2>Education & <em>Experience</em></h2></Reveal><div className="timeline">
   <Reveal className="timeline-item active"><span/><small>EDUCATION · 2024 — PRESENT</small><h3>BSc (Hons) in Creative Computing</h3><p><strong>Specialization in Interactive Media</strong><br/>Sri Lanka Institute of Information Technology (SLIIT)</p></Reveal>
  <Reveal className="timeline-item"><span/><small>ACADEMIC EXPERIENCE · PRESENT</small><h3>Interactive Media &amp; University Projects</h3><p>Developing projects across <strong>UI/UX design, branding, web development, multimedia, and interactive experiences</strong> as part of my undergraduate studies.</p><p className="timeline-detail">Selected Work: CelesTea • Movie Rental System • VR / Interactive Media Projects</p></Reveal>
  <Reveal className="timeline-item"><span/><small>PERSONAL PROJECTS · 2026 — PRESENT</small><h3>Independent Brand &amp; Digital Projects</h3><p>Creating self-initiated branding and digital design projects exploring <strong>brand identity, packaging, product presentation, UI design, and visual storytelling.</strong></p><p className="timeline-detail">VERALYA • ALPENOIRE • W</p></Reveal>
  <Reveal className="timeline-item"><span/><small>EXTRACURRICULAR &amp; LEADERSHIP · 2017 — PRESENT</small><h3>Leadership, Music &amp; Student Activities</h3><p>Actively involved in <strong>student leadership, university music, classical music, competitions, and student committee activities</strong>, strengthening my skills in <strong>leadership, teamwork, communication, and creativity.</strong></p><p className="timeline-detail">Head Prefect • SLIIT Music Band • Music Visharadh • All Island Music Competition • Interactive Media Student Committee</p></Reveal>
 </div></section>

 <Contact/>
 </>}

function Contact(){return <section id="contact" className="section contact"><div className="contact-top"><Reveal><Eyebrow>Let’s connect</Eyebrow><h2>Let’s Create Something <em>Meaningful.</em></h2><p>I am currently open to internship opportunities, creative collaborations, and projects in interactive media, brand design, UX/UI, digital marketing, and social media design.</p></Reveal><Reveal className="direct-contact"><span className="chapter">DIRECT CONTACT</span><h3>Start a conversation</h3><a href={`tel:${links.phone.replace(/\s/g,'')}`}><Phone/><span><small>PHONE</small><b>{links.phone}</b></span><ArrowUpRight/></a><a href={`mailto:${links.email}`}><Mail/><span><small>EMAIL</small><b>{links.email}</b></span><ArrowUpRight/></a><a href={links.linkedin} target="_blank" rel="noreferrer"><Linkedin/><span><small>LINKEDIN</small><b>Janadi Wickramasinghe</b></span><ArrowUpRight/></a></Reveal></div></section>}
